on: 
  push:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Continuous Intergration action step
      id: ci
      uses: ./ #to use the action.yml in this current dir
      with:
        this-ci-run: 'Yello from CI'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.ci.outputs.time }}"